name = "tpc-global"
compatibility_date = "2024-02-09"

[build]
command = "npm run export"
publish = "out"

pages_build_output_dir = "out"

[env.production]
NODE_ENV = "production"

[env.preview]
NODE_ENV = "development"
